import { defineConfig } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));

// Chromium flags shared by every project that needs real WebRTC between real
// browser contexts. Kept in one place so the benchmark cannot drift from the
// mesh tests on the things that change results (mDNS-hidden candidates would
// stop peers connecting at all; the autoplay policy would stop audio playing).
const WEBRTC_ARGS = [
  '--use-fake-device-for-media-stream',
  '--use-fake-ui-for-media-stream',
  '--autoplay-policy=no-user-gesture-required',
  // Use real loopback host candidates instead of mDNS-hidden ones, so
  // peer-to-peer ICE actually connects under automation.
  '--disable-features=WebRtcHideLocalIpsWithMdns',
];

export default defineConfig({
  testDir: './tests/e2e',
  timeout: 30_000,
  // V8 JS-coverage report (opt-in via COVERAGE=1 — see `make coverage-e2e`).
  globalTeardown: process.env.COVERAGE ? './tests/e2e/coverage-teardown.js' : undefined,
  use: {
    baseURL: 'http://127.0.0.1:8080',
    trace: 'on-first-retry',
  },
  webServer: {
    command: 'npx --yes serve src -l 8080',
    url: 'http://127.0.0.1:8080',
    reuseExistingServer: true,
    timeout: 120_000,
  },
  projects: [
    // Fast, deterministic suite (pure-logic unit tests + UI flows). Excludes the
    // multi-peer mesh tests so it stays quick and flake-free.
    {
      name: 'unit',
      grepInvert: /@mesh/,
    },
    // Multi-peer mesh tests: real PeerJS + WebRTC between isolated Chromium
    // contexts. Needs fake media and loopback host ICE candidates. Allowed to
    // retry since real WebRTC negotiation can be momentarily slow.
    {
      name: 'mesh',
      grep: /@mesh/,
      retries: 2,
      // Headroom for heartbeat-timeout host-loss detection (~7s) plus connect
      // retries, including tests that chain two sequential migrations.
      timeout: 90_000,
      use: {
        launchOptions: { args: WEBRTC_ARGS },
      },
    },
    // Performance benchmark. Its own testDir, so it cannot be collected by the
    // unit or mesh projects however they are grepped, and `npx playwright test`
    // with no --project is the only way to reach it by accident — which is why
    // `make coverage-e2e` names its projects explicitly.
    //
    // No retries: a retried benchmark would silently report the luckiest of
    // three runs. If a run does not complete, that is the result.
    {
      name: 'bench',
      testDir: './tests/bench',
      retries: 0,
      timeout: 300_000,
      use: {
        launchOptions: {
          args: [
            ...WEBRTC_ARGS,
            // Chromium's built-in fake mic is a 440 Hz sine, which Opus encodes
            // far below the 32 kb/s ceiling the app sets — every bandwidth
            // number taken against it would understate a real call. This file
            // is speech-shaped and seeded, so runs stay comparable.
            // Generated by `make bench-audio` (scripts/gen-bench-audio.mjs).
            `--use-file-for-fake-audio-capture=${resolve(ROOT, 'tests/bench/assets/bench-speech.wav')}`,
            // Same argument for the camera: the built-in fake device is a flat
            // gradient with a bouncing ball, which an encoder predicts almost
            // perfectly and codes at a fraction of CAMERA_MAX_BITRATE. This
            // file is a textured room with a moving subject and sensor grain.
            // Generated by `make bench-video` (scripts/gen-bench-video.mjs).
            `--use-file-for-fake-video-capture=${resolve(ROOT, 'tests/bench/assets/bench-scene.y4m')}`,
            // getDisplayMedia() has no automation UI, so without this the
            // screen-share scenario can only ever time out on a picker nobody
            // is there to click.
            '--auto-select-desktop-capture-source=Entire screen',
          ],
        },
      },
    },
  ],
});
